version: "3.8"

services:
  edms-gateway-staging:
    image: benzidarwin/staging-gateway:latest
    ports:
      - "8787:8787"
    depends_on:
      - file-management
      - workflows
      - tasks
      - forms
    networks:
      - edms-network-staging

  file-management-staging:
    image: benzidarwin/staging-file-management:latest
    ports:
      - "8081:8081"
    environment:
      - STORAGE_LOCATION=/app/storage
      - SECRET_KEY=/app/key/keyfile.key  
      
    volumes:
      - ./storage:/app/storage
      - ./key:/app/key  
    networks:
      - edms-network-staging

  workflows-staging:
    image: benzidarwin/staging-workflows:latest
    ports:
      - "8082:8082"
    networks:
      - edms-network-staging

  tasks-staging:
    image: benzidarwin/staging-tasks:latest
    ports:
      - "8083:8083"
    networks:
      - edms-network-staging

  forms-staging:
    image: benzidarwin/staging-forms:latest
    ports:
      - "8084:8084"
    networks:
      - edms-network-staging

networks:
  edms-network-staging:
    driver: bridge
