services:
  edms-gateway:
    build:
      context: ./gateway
    ports:
      - "8787:8787" # Exposed port is different for staging
    depends_on:
      - file-management
      - workflows
      - tasks
    networks:
      - edms-network

  file-management:
    build:
      context: ./file-management
    environment:
      - STORAGE_LOCATION=/app/storage
      - SECRET_KEY=/app/key/keyfile.key
    volumes:
      - ./storage:/app/storage
      - ./key:/app/key
    ports:
      - "8081:8081" # Exposed port is different for staging
    networks:
      - edms-network

  workflows:
    build:
      context: ./workflows
    ports:
      - "8082:8082" # Exposed port is different for staging
    networks:
      - edms-network
  
  tasks:
    build:
      context: ./tasks
    ports:
      - "8083:8083" # Exposed port is different for staging
    networks:
      - edms-network

  forms:
    build:
      context: ./forms
    ports:
      - "8084:8084" # Exposed port is different for staging
    networks:
      - edms-network

networks:
  edms-network:
    driver: bridge
