services:
  edms-gateway:
    image: benzidarwin/staging-gateway:latest
    ports:
      - "8787:8787" # Exposed port is different for staging
    depends_on:
      - file-management
      - workflows

  file-management:
    image: benzidarwin/staging-file-management:latest
    ports:
      - "8081:8081" # Exposed port is different for staging

  workflows:
    image: benzidarwin/staging-workflows:latest
    ports:
      - "8082:8082" # Exposed port is different for staging
