version: "3.8"

services:
  edms-gateway:
    image: benzidarwin/staging-gateway:latest
    ports:
      - "8787:8787"
    depends_on:
      - file-management
      - workflows
      - forms
    networks:
      - edms-network

  file-management:
    image: benzidarwin/staging-file-management:latest
    ports:
      - "8081:8081"
    environment:
      - STORAGE_LOCATION=/app/storage
      - SECRET_KEY=/app/key/keyfile.key  
    volumes:
      - storage-data:/app/storage
      - key-data:/app/key
    networks:
      - edms-network

  workflows:
    image: benzidarwin/staging-workflows:latest
    ports:
      - "8082:8082"
    networks:
      - edms-network

  forms:
    image: benzidarwin/staging-forms:latest
    ports:
      - "8084:8084"
    networks:
      - edms-network

networks:
  edms-network:
    driver: bridge

volumes:
  storage-data:
  key-data: