version: "3.8"

services:
  edms-gateway:
    build:
      context: ./gateway
    env_file:
      - .env
    ports:
      - "8787:8787"
    depends_on:
      - file-management
      - workflows
      - tasks
      - forms
    networks:
      - edms-network

  file-management:
    build:
      context: ./file-management
    env_file:
      - .env
    environment:
      - STORAGE_LOCATION=/app/storage
      - SECRET_KEY=/app/key/keyfile.key
    volumes:
      - storage-data:/app/storage
      - key-data:/app/key
    ports:
      - "8081:8081"
    networks:
      - edms-network

  workflows:
    build:
      context: ./workflows
    env_file:
      - .env
    ports:
      - "8082:8082"
    networks:
      - edms-network
  
  tasks:
    build:
      context: ./tasks
    env_file:
      - .env
    ports:
      - "8083:8083"
    networks:
      - edms-network

  forms:
    build:
      context: ./forms
    env_file:
      - .env
    ports:
      - "8084:8084"
    networks:
      - edms-network

networks:
  edms-network:
    driver: bridge

volumes:
  storage-data:
  key-data:
