version: '3.8'

services:
  edms-gateway:
    image: benzidarwin/gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - file-management
      - workflows

  file-management:
    image: benzidarwin/file-management:latest
    ports:
      - "8081:8081"

  workflows:
    image: benzidarwin/workflows:latest
    ports:
      - "8082:8082"
