version: "3.8"

services:
  edms-gateway:
    image: benzidarwin/edms-gateway:latest
    env_file:
      - .env
    ports:
      - "8787:8787"
    depends_on:
      - file-management
      - workflows
      - tasks
      - forms
    networks:
      - edms-network

  file-management:
    image: benzidarwin/edms-file-management:latest
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      - STORAGE_LOCATION=/app/storage
      - SECRET_KEY=/app/key/keyfile.key
    volumes:
      - storage-data:/app/storage
      - key-data:/app/key
    networks:
      - edms-network

  workflows:
    image: benzidarwin/edms-workflows:latest
    env_file:
      - .env
    ports:
      - "8082:8082"
    networks:
      - edms-network

  tasks:
    image: benzidarwin/edms-tasks:latest
    env_file:
      - .env
    ports:
      - "8083:8083"
    networks:
      - edms-network

  forms:
    image: benzidarwin/edms-forms:latest
    env_file:
      - .env
    ports:
      - "8084:8084"
    networks:
      - edms-network

networks:
  edms-network:
    driver: bridge

volumes:
  storage-data:
  key-data: