name: Deploy Docker Services (Staging)

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push edms-gateway Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/staging-gateway:latest ./gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/staging-gateway:latest

      - name: Build and Push file-management Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/staging-file-management:latest ./file-management
          docker push ${{ secrets.DOCKER_USERNAME }}/staging-file-management:latest

      - name: Build and Push workflows Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/staging-workflows:latest ./workflows
          docker push ${{ secrets.DOCKER_USERNAME }}/staging-workflows:latest

      - name: Log out of Docker Hub
        run: docker logout
